name: Build and Pre-release deb
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm
          
      - name: Build deb
        run: ./package.sh

      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/heads/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.branch_name.outputs.branch_name }}
          release_name: Release ${{ steps.branch_name.outputs.branch_name }}
          draft: false
          prerelease: true

      - name: Find deb files
        id: find_deb_files
        run: |
          echo "::set-output name=debFiles::$(find . -name 'out/*.deb')"

      - name: Upload deb artifacts
        id: upload_deb
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: ${{ steps.find_deb_files.outputs.debFiles }}

      - name: Attach deb to release
        id: attach_deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_deb_files.outputs.debFiles }}
          asset_name: deb-package.deb
          asset_content_type: application/vnd.debian.binary-package
