name: Build and Pre-release deb
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm

      - name: Build deb
        run: ./package.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Get branch name
        id: branch_name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Find deb files
        id: find_deb_files
        run: |
          echo "DEB_FILES=$(find . -name 'out/*.deb')" >> $GITHUB_ENV

      - name: Upload deb artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.DEB_FILES }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.create_release.outputs.release_id }}

      - name: Attach deb to release
        id: attach_deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.DEB_FILES }}
          asset_name: deb-package.deb
          asset_content_type: application/vnd.debian.binary-package
